--liquibase formatted sql

--changeset anton:create-faculty

create table faculties
(
    id         bigint generated by default as identity
        primary key,
    color varchar(255),
    name  varchar(255)
);

alter table faculties
    owner to student;